services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      TYPO3\CMS\Core\Messaging\FlashMessageQueue $flashMessageQueue: '@oauth2_client.flash_message_queue'

  CoStack\Oauth2Client\:
    resource: '../Classes/*'

  oauth2_client.flash_message_queue:
    class: TYPO3\CMS\Core\Messaging\FlashMessageQueue
    factory: [ '@TYPO3\CMS\Core\Messaging\FlashMessageService', 'getMessageQueueByIdentifier' ]
    arguments: [ 'oauth2_client' ]

  CoStack\Oauth2Client\Localization\LanguageService:
    factory: [ '@CoStack\Oauth2Client\Localization\LanguageServiceFactory', 'create' ]
